name: Release New Version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@1.1.2
      with:
        regex_pattern: "(?:version:)(?:\\s)?(\\d+\\.\\d+\\d+.+)\\n?"
        root: ./.gorc
        tag_prefix: "v"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"