name: Release New Version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: butlerlogic/action-autotag@1.1.4
      with:
        regex_pattern: "(version:)(\\s)?(?<version>\\d+\\.\\d+\\.\\d+(.+)?)\\n?"
        root: ./.gorc
        tag_prefix: "v"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"